import { Montserrat, Roboto } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({
  weight: "400", 
  subsets: ["latin"],
});

// const roboto = Roboto({
//   weight: "500",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Ribs & Rythm staff portal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
